language: java
sudo: false # faster builds

script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov

after_success:
  - codecov