# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Debug mod
debug: false

# Typ serveru
server: lobby

# Zmena casu podle real-time
timer: false

## EVENTY ##
events:
 # Vanocni update zahrnujici kalendar + efekty
 christmas: false
 # Efekty po lobby (ohnostroje)
 silvester: false