# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Debug mod
debug: false

# Typ serveru
server: lobby

# Generator vitezu! POUZE OHUB!
ticket-winner: false