name: WakesLobby	
main: cz.wake.lobby.Main
version: 1.6
author: MrWakeCZ
softdepend: [CrateKeys]
depend: [Multiverse-Core]
commands:
  wlobby:
    description: Info o profilu!
  wl:
    description: Info o profilu!
  stats:
    description: Statistiky hracu
  sbperms:
    description: Addon na Skybox
  cbperms:
    description: Addon na CraftBoxy
  vip:
    description: Menu pro nakup VIP
  survival:
    description: Server teleport
  skyblock:
    description: Server teleport
  creative:
    description: Server teleport
  creative2:
    description: Server teleport
  prison:
    description: Server teleport
  vanilla:
    description: Server teleport
  bedwars:
    description: Server teleport
  skywars:
    description: Server teleport
  arcade:
    description: Server teleport
  skygiants:
    description: Server teleport
  vanillasb:
    description: Server teleport

permissions:
  craftlobby.pristup:
    description: Beta test
