name: CraftLobby
main: cz.wake.lobby.Main
version: "1.8"
api-version: "1.12"
author: MrWakeCZ
softdepend: [RogueParkour]
depend: [Multiverse-Core,CraftCore]
commands:
  clobby:
    description: Info o profilu!
    aliases: [cl]
  vip:
    description: Profil pro nakup VIP
  survival:
    description: Server teleport
  skyblock:
    description: Server teleport
  creative:
    description: Server teleport
  prison:
    description: Server teleport
  vanilla:
    description: Server teleport
  vanillasb:
    description: Server teleport
  oldcrafttokens:
    description: Jjjj tokeny
  kalendar:
    description: Vanoce! :D
  link:
    description: Prepojeni Discordu s MC

permissions:
  craftlobby.pristup:
    description: Beta test
