name: CraftLobby
main: cz.wake.lobby.Main
version: "2.1"
api-version: "1.15"
author: MrWakeCZ
softdepend: [RogueParkour,LuckPerms]
depend: [Multiverse-Core,CraftCore,NPCLibPlugin]

permissions:
  craftlobby.pristup:
    description: Beta test
