name: WakesLobby	
main: cz.wake.lobby.Main
version: 1.6
author: MrWakeCZ
softdepend: [CrateKeys]
depend: [Vault]
commands:
  wlobby:
    description: Info o profilu!
  wl:
    description: Info o profilu!
  stats:
    description: Statistiky hracu
  sbperms:
    description: Addon na Skybox
  cbperms:
    description: Addon na CraftBoxy
  changepassword:
    description: Prikaz na zmenu hesla pro Warez
  kalendar:
    description: Kalendar ne...
  ticket:
    description: Ticketyyy
permissions:
  craftlobby.pristup:
    description: Beta test
