name: WakesLobby	
main: cz.wake.plugins.Main
version: 1.2.30
author: MrWakeCZ
depend: [Vault]
commands:
  wlobby:
    description: Info o profilu!
  wl:
    description: Info o profilu!
  stats:
    description: Statistiky hracu
permissions:
  craftlobby.pristup:
    description: Beta test
